runtime: python312

entrypoint: gunicorn -w 4 -k uvicorn.workers.UvicornWorker main:app

instance_class: B2

env_variables:
  PYTHONUNBUFFERED: "true"

handlers:
  - url: /static
    static_dir: static

  - url: /.*
    script: auto
