runtime: python312
env: flex
entrypoint: gunicorn -w 4 -k -b :$PORT uvicorn.workers.UvicornWorker app:app

instance_class: F1

automatic_scaling:
  max_instances: 1

handlers:
  - url: /static
    static_dir: static

  - url: /.*
    script: auto

env_variables:
  PYTHONUNBUFFERED: "true"
