runtime: python312
env: flex
entrypoint: gunicorn -b :$PORT main:app

instance_class: F1

automatic_scaling:
  max_num_instances: 1
  cool_down_period_sec: 180
  cpu_utilization:
    target_utilization: 0.6

handlers:
  - url: /static
    static_dir: static

  - url: /.*
    script: auto

env_variables:
  PYTHONUNBUFFERED: "true"
