runtime: python312
instance_class: B4

basic_scaling:
  max_instances: 1
  idle_timeout: 5m

handlers:
- url: /.*
  script: auto
    http_headers:
      Access-Control-Allow-Origin: https://moodle.oulu.fi
